version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

jobs:
  containers:
    executor: python

    parameters:
      repo:
        type: string
      maintainer:
        type: string

    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: Docker Hub login
          command: |
            if [ -n "$DOCKER_HUB_USERNAME" ]; then
              docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            else
              echo "Missing Docker Hub credentials"
              exit 1
            fi

      - restore_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirments.txt

      - save_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/lib/python3.9/site-packages"

      - run:
          name: Build images
          command: |
            python3 build.py --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD -m << parameters.maintainer >> -r << parameters.repo >> matrix.json

workflows:
  version: 2
  commit:
    jobs:
      - containers:
          repo: solarbotics/arduio-cli
          maintainer: support@solarbotics.com
          context:
            - dockerhub
