version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  containers:
    executor: python

    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: Docker Hub login
          command: |
            if [ -n "$DOCKERHUB_USERNAME" ]; then
              docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            else
              echo "Missing Docker Hub credentials"
              exit 1
            fi

workflows:
  version: 2
  commit:
    jobs:
      - container:
          context:
            - dockerhub
